name: flut_base_app_the_movie_db_clone
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.3
  dio: ^5.4.3+1
  http: ^1.2.1
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4
  build_runner: ^2.4.9
  faker: ^2.1.0
  responsive_builder: ^0.7.0
  recase: ^4.1.0
  enum_to_string: ^2.0.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/